resources:
  pipelines:
    - pipeline: PipelineA
      source: leriksen.marco-source
      trigger: true

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
